# Generated by Django 5.2.3 on 2025-08-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0005_alter_prato_foto_prato'),
        ('churras', '0005_alter_prato_foto_prato_alter_prato_funcionario'),
    ]

    operations = [
    ]
