# Generated by Django 5.2.3 on 2025-08-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0006_alter_prato_foto_prato'),
        ('churras', '0006_merge_20250802_0910'),
    ]

    operations = [
    ]
